<template>

    <el-table :data="userinfo" border class="more-work-table">
        <el-table-column prop="createTime" label="创建时间" />
        <el-table-column prop="name" label="姓名"/>
        <el-table-column prop="dept" label="部门" />
        <el-table-column prop="role" label="角色" />
        <el-table-column prop="phoneNumber" label="联系方式" width="125" />
        <el-table-column prop="moreWorkTime" label="加班时间" />

        <el-table-column label="操作" width="170">
            <template #default="scope">
                <el-button type="primary">同意</el-button>
                <el-button type="danger">拒绝</el-button>
            </template>
        </el-table-column>
    </el-table>

</template>

<script setup>

const userinfo = [
    {
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },
    {
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },
    {
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },
    {
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },
    {
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },{
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    },
    {
        select: 'select',
        name: 'name',
        sex: '男',
        age: 19,
        dept: '开发部',
        role: '总经理',
        phoneNumber: '18336597584',
        address: '黑龙江省哈尔滨市香坊区',
        entryTime: '2022-09-11',
        state: '工作中',
        option: 'option',
    }
]

</script>

<style scoped>
.more-work-table {
    width: 100%;
}
</style>